version: '3.1'
services:
  currency_db:
    container_name: currency_container
    image: postgres
    restart: always
    ports:
      - "5499:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: usman
      POSTGRES_DB: cur